package com.faucet.greendao.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DBCOMPANY_USER_EMAIL_INFO".
 */
@Entity
public class DBCompanyUserEmailInfo {

    @Id(autoincrement = true)
    private Long id;
    private String email;
    private Long foreign_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getForeign_id() {
        return foreign_id;
    }

    public void setForeign_id(Long foreign_id) {
        this.foreign_id = foreign_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
