package com.faucet.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.faucet.greendao.bean.DBUserInfo;
import com.faucet.greendao.bean.DBValidationMessage;
import com.faucet.greendao.bean.DBCompanyUserInfo;
import com.faucet.greendao.bean.DBCompanyUserTelInfo;
import com.faucet.greendao.bean.DBCompanyUserEmailInfo;

import com.faucet.greendao.dao.DBUserInfoDao;
import com.faucet.greendao.dao.DBValidationMessageDao;
import com.faucet.greendao.dao.DBCompanyUserInfoDao;
import com.faucet.greendao.dao.DBCompanyUserTelInfoDao;
import com.faucet.greendao.dao.DBCompanyUserEmailInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBUserInfoDaoConfig;
    private final DaoConfig dBValidationMessageDaoConfig;
    private final DaoConfig dBCompanyUserInfoDaoConfig;
    private final DaoConfig dBCompanyUserTelInfoDaoConfig;
    private final DaoConfig dBCompanyUserEmailInfoDaoConfig;

    private final DBUserInfoDao dBUserInfoDao;
    private final DBValidationMessageDao dBValidationMessageDao;
    private final DBCompanyUserInfoDao dBCompanyUserInfoDao;
    private final DBCompanyUserTelInfoDao dBCompanyUserTelInfoDao;
    private final DBCompanyUserEmailInfoDao dBCompanyUserEmailInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBUserInfoDaoConfig = daoConfigMap.get(DBUserInfoDao.class).clone();
        dBUserInfoDaoConfig.initIdentityScope(type);

        dBValidationMessageDaoConfig = daoConfigMap.get(DBValidationMessageDao.class).clone();
        dBValidationMessageDaoConfig.initIdentityScope(type);

        dBCompanyUserInfoDaoConfig = daoConfigMap.get(DBCompanyUserInfoDao.class).clone();
        dBCompanyUserInfoDaoConfig.initIdentityScope(type);

        dBCompanyUserTelInfoDaoConfig = daoConfigMap.get(DBCompanyUserTelInfoDao.class).clone();
        dBCompanyUserTelInfoDaoConfig.initIdentityScope(type);

        dBCompanyUserEmailInfoDaoConfig = daoConfigMap.get(DBCompanyUserEmailInfoDao.class).clone();
        dBCompanyUserEmailInfoDaoConfig.initIdentityScope(type);

        dBUserInfoDao = new DBUserInfoDao(dBUserInfoDaoConfig, this);
        dBValidationMessageDao = new DBValidationMessageDao(dBValidationMessageDaoConfig, this);
        dBCompanyUserInfoDao = new DBCompanyUserInfoDao(dBCompanyUserInfoDaoConfig, this);
        dBCompanyUserTelInfoDao = new DBCompanyUserTelInfoDao(dBCompanyUserTelInfoDaoConfig, this);
        dBCompanyUserEmailInfoDao = new DBCompanyUserEmailInfoDao(dBCompanyUserEmailInfoDaoConfig, this);

        registerDao(DBUserInfo.class, dBUserInfoDao);
        registerDao(DBValidationMessage.class, dBValidationMessageDao);
        registerDao(DBCompanyUserInfo.class, dBCompanyUserInfoDao);
        registerDao(DBCompanyUserTelInfo.class, dBCompanyUserTelInfoDao);
        registerDao(DBCompanyUserEmailInfo.class, dBCompanyUserEmailInfoDao);
    }
    
    public void clear() {
        dBUserInfoDaoConfig.clearIdentityScope();
        dBValidationMessageDaoConfig.clearIdentityScope();
        dBCompanyUserInfoDaoConfig.clearIdentityScope();
        dBCompanyUserTelInfoDaoConfig.clearIdentityScope();
        dBCompanyUserEmailInfoDaoConfig.clearIdentityScope();
    }

    public DBUserInfoDao getDBUserInfoDao() {
        return dBUserInfoDao;
    }

    public DBValidationMessageDao getDBValidationMessageDao() {
        return dBValidationMessageDao;
    }

    public DBCompanyUserInfoDao getDBCompanyUserInfoDao() {
        return dBCompanyUserInfoDao;
    }

    public DBCompanyUserTelInfoDao getDBCompanyUserTelInfoDao() {
        return dBCompanyUserTelInfoDao;
    }

    public DBCompanyUserEmailInfoDao getDBCompanyUserEmailInfoDao() {
        return dBCompanyUserEmailInfoDao;
    }

}
