package com.faucet.greendao.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.faucet.greendao.bean.DBValidationMessage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBVALIDATION_MESSAGE".
*/
public class DBValidationMessageDao extends AbstractDao<DBValidationMessage, Long> {

    public static final String TABLENAME = "DBVALIDATION_MESSAGE";

    /**
     * Properties of entity DBValidationMessage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Message = new Property(1, String.class, "message", false, "MESSAGE");
        public final static Property Foreign_id = new Property(2, Long.class, "foreign_id", false, "FOREIGN_ID");
    }

    private Query<DBValidationMessage> dBUserInfo_MessageQuery;

    public DBValidationMessageDao(DaoConfig config) {
        super(config);
    }
    
    public DBValidationMessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBVALIDATION_MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MESSAGE\" TEXT," + // 1: message
                "\"FOREIGN_ID\" INTEGER);"); // 2: foreign_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBVALIDATION_MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBValidationMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(2, message);
        }
 
        Long foreign_id = entity.getForeign_id();
        if (foreign_id != null) {
            stmt.bindLong(3, foreign_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBValidationMessage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(2, message);
        }
 
        Long foreign_id = entity.getForeign_id();
        if (foreign_id != null) {
            stmt.bindLong(3, foreign_id);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBValidationMessage readEntity(Cursor cursor, int offset) {
        DBValidationMessage entity = new DBValidationMessage();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBValidationMessage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMessage(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setForeign_id(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBValidationMessage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBValidationMessage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBValidationMessage entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "message" to-many relationship of DBUserInfo. */
    public List<DBValidationMessage> _queryDBUserInfo_Message(Long foreign_id) {
        synchronized (this) {
            if (dBUserInfo_MessageQuery == null) {
                QueryBuilder<DBValidationMessage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Foreign_id.eq(null));
                dBUserInfo_MessageQuery = queryBuilder.build();
            }
        }
        Query<DBValidationMessage> query = dBUserInfo_MessageQuery.forCurrentThread();
        query.setParameter(0, foreign_id);
        return query.list();
    }

}
